version: '3.1'

services:

  db:
    container_name: mydb
    image: postgres:15.1
    restart: unless-stopped
    environment:
      POSTGRES_DB: local
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      TZ: Asia/Bangkok
    ports:
      - 3306:5432

  adminer:
    container_name: admin
    image: adminer
    restart: always
    ports:
      - 8080:8080
